app/forms/account_add.py
from flask_login import current_user
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.fields.core import DateField, SelectField
from wtforms.validators import DataRequired, Length, Email
from app.models import User


class AccountAddForm(FlaskForm):
    def __init__(self, user=None):
        super().__init__()
        if user:
            if (
                current_user.role.name == "distributor"
                or current_user.role.name == "reseller"
            ):
                self.reseller.choices = [sub.username for sub in current_user.subs]
            elif current_user.role.name == "sub_reseller":
                self.reseller.choices = [current_user.username]
            else:
                users = User.query.filter(User.deleted == False) # noqa E712
                self.reseller.choices = [sub.username for sub in users]

    reseller = SelectField("Reseller", choices=[])
    sub_duration = SelectField("Subscription", choices=[
        (1, '1 Month'),
        (3, '3 Months'),
        (6, '6 Months'),
        (12, '12 Months')
    ], default=1)
    sub_activate_date = DateField("Activation Date")
    submit = SubmitField(label="Save")


class NewAccountForm(FlaskForm):
    ecc_id = StringField("Ecc ID", [DataRequired(), Length(min=7, max=7)])
    ecc_password = StringField("ECC Password", [DataRequired()])
    ad_login = StringField("Login", [DataRequired()])
    ad_password = StringField("AD Password", [DataRequired()])
    email = StringField("Email", [DataRequired(), Email(5, 45)])
    sim = StringField("Sim")
    comment = TextAreaField("Comments")
    submit = SubmitField("Invisible submit")

app/forms/account_edit.py
from flask_login import current_user
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.fields.core import SelectField
from wtforms.validators import DataRequired, Length, Email
from app.models import User


class AccountEditForm(FlaskForm):
    def __init__(self, user=None):
        super().__init__()
        if user:
            if (
                current_user.role.name == "distributor"
                or current_user.role.name == "reseller"
            ):
                self.reseller.choices = [sub.username for sub in current_user.subs]
            elif current_user.role.name == "sub_reseller":
                self.reseller.choices = [current_user.username]
            else:
                users = User.query.filter(User.deleted == False) # noqa E712
                self.reseller.choices = [sub.username for sub in users]

    email = StringField("Email", [DataRequired(), Email(5, 45)])
    ad_login = StringField("Login", [DataRequired()])
    ad_password = StringField("AD Password", [DataRequired()])
    ecc_id = StringField("Ecc ID", [DataRequired(), Length(min=7, max=7)])
    ecc_password = StringField("ECC Password", [DataRequired()])
    sim = StringField("Sim")
    reseller = SelectField("Reseller", choices=[])
    comment = TextAreaField("Comments")
    submit = SubmitField()

app/views/account.py
from datetime import datetime
from dateutil.relativedelta import relativedelta
import base64
import io
from sqlalchemy import or_, func
from flask import (
    render_template,
    Blueprint,
    jsonify,
    flash,
    redirect,
    url_for,
    request,
    session,
)
from flask_login import login_required, current_user
from app.models import Account, User, Subscription
from app.forms import (
    AccountAddForm,
    DeviceForm,
    AccountEditForm,
    SubscriptionForm,
    NewAccountForm,
)
from app.logger import log
from app.controllers import create_qrcode, generate_password, MDM, role_required
from app.controllers.ldap import LDAP
from app.controllers.ssh_ps import RemoteMatrix
from config import BaseConfig as config

account_blueprint = Blueprint("account", __name__)


@account_blueprint.route("/accounts")
@login_required
def index():
    if 'accounts' in session:
        session.pop('accounts')
    return render_template("pages/accounts.html")


@account_blueprint.route("/add_account", methods=["GET", "POST"])
@login_required
def add_account():
    form = AccountAddForm(user=current_user)
    if request.method == "GET":
        form.reseller.data = current_user.username
        form.sub_activate_date.data = datetime.date(datetime.now())
        if "accounts" not in session:
            acc = {}
            ecc_id = Account.gen_ecc_id()
            ad_login = Account.gen_ad_login()
            forms = [NewAccountForm()]
            forms[0].ecc_id.data = ecc_id
            forms[0].ecc_password.data = generate_password()
            forms[0].ad_login.data = ad_login
            forms[0].ad_password.data = generate_password()
            forms[0].email.data = f"{ad_login}@kryptr.li"
            acc["ecc_id"] = forms[0].ecc_id.data
            acc["ecc_password"] = forms[0].ecc_password.data
            acc["ad_login"] = forms[0].ad_login.data
            acc["ad_password"] = forms[0].ad_password.data
            acc["email"] = forms[0].email.data
            acc["sim"] = forms[0].sim.data
            acc["comment"] = forms[0].comment.data
            session['accounts'] = [acc]
        else:
            forms = []
            for acc in session["accounts"]:
                sub_form = NewAccountForm()
                if not acc:
                    new_acc = {}
                    ecc_id = Account.gen_ecc_id()
                    ad_login = Account.gen_ad_login()
                    sub_form.ecc_id.data = ecc_id
                    sub_form.ecc_password.data = generate_password()
                    sub_form.ad_login.data = ad_login
                    sub_form.ad_password.data = generate_password()
                    sub_form.email.data = f"{ad_login}@kryptr.li"
                    new_acc["ecc_id"] = sub_form.ecc_id.data
                    new_acc["ecc_password"] = sub_form.ecc_password.data
                    new_acc["ad_login"] = sub_form.ad_login.data
                    new_acc["ad_password"] = sub_form.ad_password.data
                    new_acc["email"] = sub_form.email.data
                    new_acc["sim"] = sub_form.sim.data
                    new_acc["comment"] = sub_form.comment.data
                    session['accounts'][-1] = new_acc
                else:
                    sub_form.ecc_id.data = acc["ecc_id"]
                    sub_form.ecc_password.data = acc["ecc_password"]
                    sub_form.ad_login.data = acc["ad_login"]
                    sub_form.ad_password.data = acc["ad_password"]
                    sub_form.email.data = acc["email"]
                    sub_form.sim.data = acc["sim"]
                    sub_form.comment.data = acc["comment"]
                forms.append(sub_form)
        return render_template(
            "base_add_edit.html",
            include_header="components/_account-add.html",
            form=form,
            forms=enumerate(forms),
            description_header=("Add accounts"),
            cancel_link=url_for("account.index"),
            action_url=url_for("account.add_account"),
            count=len(forms)
        )
    if form.validate_on_submit():
        reseller = User.query.filter(User.username == form.reseller.data).first()
        instructions = []
        for account in session["accounts"]:
            acc = Account(
                ecc_id=account["ecc_id"],
                ecc_password=account["ecc_password"],
                email=account["email"],
                ad_login=account["ad_login"],
                ad_password=account["ad_password"],
                sim=account["sim"],
                reseller_id=reseller.id,
                comment=account["comment"],
            ).save()
            Subscription(
                account_id=acc.id,
                months=form.sub_duration.data,
                activation_date=form.sub_activate_date.data,
            ).save()
            log(
                log.INFO,
                "Generated ecc_id is. [%s] for account id [%s]",
                acc.ecc_id,
                acc.id,
            )
            if config.LDAP_SERVER:
                conn = LDAP()
                user = conn.add_user(acc.ad_login)
                if not user:
                    log(log.WARNING, "Could not add user")
                    flash("Could not add user.", "danger")
                    return redirect(url_for("account.add_account"))
                error_message = user.reset_password(acc.ad_password)
                if error_message:
                    log(log.ERROR, "%s", error_message)
                    flash(error_message, "danger")
                    return redirect(url_for("account.add_account"))
                MDM().sync()
            if config.MATRIX_SERVER_HOST_NAME:
                matrix = RemoteMatrix()
                matrix.add_user(acc)
            account_data = {}
            account_data['acc'] = acc
            qrcode = create_qrcode(acc)
            data = io.BytesIO()
            qrcode.save(data, "JPEG")
            encoded_img_data = base64.b64encode(data.getvalue())
            img = encoded_img_data.decode("utf-8")
            account_data['img'] = img
            instructions.append(account_data)
        log(log.INFO, "Account(s) creation successful.")
        flash("Account(s) creation successful.", "success")
        session.pop('accounts')
        return render_template(
            "base_add_edit.html",
            include_header="components/_account-instructions.html",
            description_header=("Accounts Info"),
            cancel_link=url_for("account.index"),
            instructions=instructions
        )

    elif form.is_submitted():
        log(log.ERROR, "Submit failed: %s", form.errors)
    return render_template(
        "base_add_edit.html",
        include_header="components/_account-add.html",
        form=form,
        description_header=("Add account"),
        cancel_link=url_for("account.index"),
        action_url=url_for("account.add_account"),
    )


@account_blueprint.route("/add_account/multiply/<int:acc_index>", methods=["POST"])
@login_required
def multiply_account(acc_index):
    form = NewAccountForm()
    if form.validate_on_submit():
        acc = session["accounts"][acc_index]
        acc["ecc_id"] = form.ecc_id.data
        acc["ecc_password"] = form.ecc_password.data
        acc["ad_login"] = form.ad_login.data
        acc["ad_password"] = form.ad_password.data
        acc["email"] = form.email.data
        acc["sim"] = form.sim.data
        acc["comment"] = form.comment.data
        session["accounts"][acc_index] = acc
        return redirect(url_for("account.add_account", _anchor=f"sub_form_{acc_index}"))


@account_blueprint.route("/add_account/add_template", methods=["GET"])
@login_required
def add_template():
    account = {}
    session['accounts'].append(account)
    acc_index = session['accounts'].index(account)
    return redirect(url_for("account.add_account", _anchor=f"sub_form_{acc_index}"))


@account_blueprint.route("/add_account/regenerate/<int:acc_index>", methods=["GET"])
@login_required
def regenerate(acc_index):
    account = session['accounts'][acc_index]
    ecc_id = Account.gen_ecc_id()
    ad_login = Account.gen_ad_login()
    account["ecc_id"] = ecc_id
    account["ecc_password"] = generate_password()
    account["ad_login"] = ad_login
    account["ad_password"] = generate_password()
    account["email"] = f"{ad_login}@kryptr.li"
    account["sim"] = ''
    account["comment"] = ''
    return redirect(url_for("account.add_account", _anchor=f"sub_form_{acc_index}"))


@account_blueprint.route("/edit_account/<int:account_id>", methods=["GET", "POST"])
@login_required
def edit_account(account_id):
    form = AccountEditForm(user=current_user)
    sub_form = SubscriptionForm()
    acc = Account.query.get(account_id)
    if acc not in current_user.accounts:
        log(
            log.ERROR,
            "User [%s] do not have permissions for acc [%s]",
            current_user,
            acc.id,
        )
        flash(f"<Access denied to account {account_id}>", "danger")
        return redirect(url_for("account.index"))
    if acc:
        if request.method == "GET":
            form.ecc_id.data = acc.ecc_id
            form.ecc_password.data = acc.ecc_password
            form.reseller.data = acc.reseller.username
            form.sim.data = acc.sim
            form.comment.data = acc.comment
            form.ad_login.data = acc.ad_login
            form.ad_password.data = acc.ad_password
            form.email.data = acc.email
            sub_form.sub_activate_date.data = datetime.date(datetime.now())
        if form.validate_on_submit():
            reseller = User.query.filter(User.username == form.reseller.data).first()
            acc.ecc_id = form.ecc_id.data
            acc.ecc_password = form.ecc_password.data
            acc.sim = form.sim.data
            acc.comment = form.comment.data
            acc.reseller_id = reseller.id
            acc.save()

app/views/auth.py
from flask import Blueprint, render_template, url_for, redirect, flash, request
from flask_login import login_user, logout_user, login_required

from app.models import User
from app.forms import LoginForm

auth_blueprint = Blueprint('auth', __name__)


@auth_blueprint.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm(request.form)
    if form.validate_on_submit():
        user = User.authenticate(form.user_id.data, form.password.data)
        if user is not None:
            login_user(user)
            flash('Login successful.', 'success')
            return redirect(url_for('account.index'))
        flash('Wrong user ID or password.', 'danger')
    return render_template('login.html', form=form)


@auth_blueprint.route('/logout')
@login_required
def logout():
    logout_user()
    flash('You were logged out.', 'info')
    return redirect(url_for('main.index'))

app/templates/components/_account-add.html
<form class="edit__form" action="{{ action_url }}" method="POST" id="main">
    <div class="edit__container">
      {{ form.hidden_tag() }}

      <div class="edit__group">
        <div class="input__wrapper">
          <label class="edit__label"> Reseller </label>
          {{ form.reseller(class="edit__input", form="main")}}
        </div>
        <div class="edit__feedback">
          {% for error in form.reseller.errors %}
          <span>{{ error }}</span>
          {% endfor %}
        </div>
      </div>

      <div class="edit__group ghost-submit">
        <div class="input__wrapper">
          <label class="edit__label"> Reseller </label>
          {{ form.reseller(class="edit__input", form="main")}}
        </div>
        <div class="edit__feedback">
          {% for error in form.reseller.errors %}
          <span>{{ error }}</span>
          {% endfor %}
        </div>
      </div>

      <div class="edit__group">
        <div class="input__wrapper">
          <label class="edit__label"> Subscribtion Activation Date </label>
          {{ form.sub_activate_date(class="edit__input", type="date", form="main")}}
        </div>
        <div class="edit__feedback">
          {% for error in form.sub_activate_date.errors %}
          <span>{{ error }}</span>
          {% endfor %}
        </div>
      </div>

      <div class="edit__group">
        <div class="input__wrapper">
          <label class="edit__label"> Renew Subscribtion </label>
          {{ form.sub_duration(class="edit__input", form="main")}}
        </div>
        <div class="edit__feedback">
          {% for error in form.sub_duration.errors %}
          <span>{{ error }}</span>
          {% endfor %}
        </div>
      </div>

      <div>
        <img src="{{ url_for('static', filename='images/loading-11.gif') }} " id="gif">
      </div>
      <div class="edit__group btn-container">
        <div class="edit__submit-btn reload-button">{{ form.submit(class="edit__submit", form="main", id="main_submit")}}</div>
      </div>

      <div class="edit__label line"></div>
    </div>
</form>

{% for i, sub_form in forms %}
<!-- before open form -->
<form class="edit__form" action="{{ url_for('account.multiply_account', acc_index=i )}}" method="POST" id="sub_form_{{i}}">
<!-- after open form -->
  <div class="edit__container">
    {{ sub_form.hidden_tag() }}

    {% if current_user.role.name == 'admin' or current_user.role.name == 'support' %}
    <div class="edit__group">
      <div class="input__wrapper">
        <label class="edit__label"> EСС </label>
        {{ sub_form.ecc_id(class="edit__input edit__spec field_{}".format(i), type="text")}}
      </div>
      <div class="edit__feedback">
        {% for error in sub_form.ecc_id.errors %}
        <span>{{ error }}</span>
        {% endfor %}
      </div>
    </div>
    {% else %}
    <div class="edit__group">
      <div class="input__wrapper">
        <label class="edit__label"> EСС </label>
        {{ sub_form.ecc_id(class="edit__input disabled field_{}".format(i), type="text", readonly="true")}}
      </div>
      <div class="edit__feedback">
        {% for error in sub_form.ecc_id.errors %}
        <span>{{ error }}</span>
        {% endfor %}
      </div>
    </div>
    {% endif %}

    <div class="edit__group">
      <div class="input__wrapper">
        <label class="edit__label"> EСС Password </label>
        {{ sub_form.ecc_password(class="edit__input edit__spec field_{}".format(i), type="text")}}
      </div>
      <div class="edit__feedback">
        {% for error in sub_form.ecc_password.errors %}
        <span>{{ error }}</span>
        {% endfor %}
      </div>
    </div>

    <div class="edit__group">
      <div class="input__wrapper">
        <label class="edit__label"> AD Login </label>
        {{ sub_form.ad_login(class="edit__input disabled field_{}".format(i), type="text",
        placeholder="Login", readonly="true")}}
      </div>
      <div class="edit__feedback">
        {% for error in sub_form.ad_login.errors %}
        <span>{{ error }}</span>
        {% endfor %}
      </div>
    </div>

    <div class="edit__group">
      <div class="input__wrapper">
        <label class="edit__label"> AD Password </label>
        {{ sub_form.ad_password(class="edit__input disabled field_{}".format(i), type="text",
        placeholder="Login", readonly="true")}}
      </div>
      <div class="edit__feedback">
        {% for error in sub_form.ad_password.errors %}
        <span>{{ error }}</span>
        {% endfor %}
      </div>
    </div>

    <div class="edit__group">
      <div class="input__wrapper">
        <label class="edit__label"> Email </label>
        {{ sub_form.email(class="edit__input disabled field_{}".format(i), type="email",
        readonly="true")}}
      </div>
      <div class="edit__feedback">
        {% for error in sub_form.email.errors %}
        <span>{{ error }}</span>
        {% endfor %}
      </div>
    </div>

    <div class="edit__group">
      <div class="input__wrapper">
        <label class="edit__label"> Sim </label>
        {{ sub_form.sim(class="edit__input field_{}".format(i), type="text")}}
      </div>
      <div class="edit__feedback">
        {% for error in sub_form.sim.errors %}
        <span>{{ error }}</span>
        {% endfor %}
      </div>
    </div>

    <div class="edit__group">
      <div class="input__wrapper">
        <label class="edit__label"> Comments </label>
        {{ sub_form.comment(class="edit__input field_{}".format(i), placeholder="Comments")}}
      </div>
      <div class="edit__feedback">
        {% for error in sub_form.comment.errors %}
        <span>{{ error }}</span>
        {% endfor %}
      </div>
    </div>

    <div class="edit__group">
      <div class="edit__submit-btn reload-button">
        <a
          type="button"
          href="{{ url_for('account.regenerate', acc_index=i) }}"
          class="edit__submit"
          >Regenerate</a
        >
      </div>
    </div>

    <div>
      <img src="{{ url_for('static', filename='images/loading-11.gif') }}" id="gif">
    </div>
    <div class="edit__group btn-container ghost-submit">
      <div class="edit__submit-btn reload-button">{{ sub_form.submit(class="edit__submit ghost-submit", id="submit_{}".format(i))}}</div>
    </div>
    <div class="edit__label line">
    </div>

  </div>
  <!-- before close form -->
</form>
<!-- after close form -->
{% endfor %}

{% if count < 5 %}
<div class="edit__group btn-container">
  <div class="edit__submit-btn reload-button">
    <a
      type="button"
      href="{{ url_for('account.add_template') }}"
      class="edit__submit"
      >+</a
    >
  </div>
</div>
{% endif %}

app/templates/components/_account-edit.html
<form class="edit__form" action="{{ url_for('account.edit_account', account_id=account_id) }}" method="POST">
  <div class="edit__container">
    {{ form.hidden_tag() }}
    {% if current_user.role.name == 'admin' or current_user.role.name == 'support' %}
    <div class="edit__group">
      <div class="input__wrapper">
        <label class="edit__label"> EСС </label>
        {{ form.ecc_id(class="edit__input edit__spec", type="text")}}
      </div>
      <div class="edit__feedback">
        {% for error in form.ecc_id.errors %}
        <span>{{ error }}</span>
        {% endfor %}
      </div>
    </div>
    {% else %}
    <div class="edit__group">
      <div class="input__wrapper">
        <label class="edit__label"> EСС </label>
        {{ form.ecc_id(class="edit__input disabled", type="text", readonly="true")}}
      </div>
      <div class="edit__feedback">
        {% for error in form.ecc_id.errors %}
        <span>{{ error }}</span>
        {% endfor %}
      </div>
    </div>
    {% endif %}

    <div class="edit__group">
      <div class="input__wrapper">
        <label class="edit__label"> EСС Password </label>
        {{ form.ecc_password(class="edit__input edit__spec", type="text")}}
      </div>
      <div class="edit__feedback">
        {% for error in form.ecc_password.errors %}
        <span>{{ error }}</span>
        {% endfor %}
      </div>
    </div>

    <div class="edit__group">
      <div class="input__wrapper">
        <label class="edit__label"> Email </label>
        {{ form.email(class="edit__input disabled", type="email",
        readonly="true")}}
      </div>
      <div class="edit__feedback">
        {% for error in form.email.errors %}
        <span>{{ error }}</span>
        {% endfor %}
      </div>
    </div>

    <div class="edit__group">
      <div class="input__wrapper">
        <label class="edit__label"> AD Login </label>
        {{ form.ad_login(class="edit__input disabled", type="text",
        placeholder="Login", readonly="true")}}
      </div>
      <div class="edit__feedback">
        {% for error in form.ad_login.errors %}
        <span>{{ error }}</span>
        {% endfor %}
      </div>
    </div>

    <div class="edit__group">
      <div class="input__wrapper">
        <label class="edit__label"> AD Password </label>
        {{ form.ad_password(class="edit__input disabled", type="text",
        placeholder="Login", readonly="true")}}
      </div>
      <div class="edit__feedback">
        {% for error in form.ad_password.errors %}
        <span>{{ error }}</span>
        {% endfor %}
      </div>
    </div>

    <div class="edit__group">
      <div class="input__wrapper">
        <label class="edit__label"> Sim </label>
        {{ form.sim(class="edit__input", type="text", )}}
      </div>
      <div class="edit__feedback">
        {% for error in form.sim.errors %}
        <span>{{ error }}</span>
        {% endfor %}
      </div>
    </div>

    <div class="edit__group">
      <div class="input__wrapper">
        <label class="edit__label"> Reseller </label>
        {{ form.reseller(class="edit__input")}}
      </div>
      <div class="edit__feedback">
        {% for error in form.reseller.errors %}
        <span>{{ error }}</span>
        {% endfor %}
      </div>
    </div>

    <div class="edit__group">
      <div class="input__wrapper">
        <label class="edit__label"> Comments </label>
        {{ form.comment(class="edit__input", placeholder="Comments")}}
      </div>
      <div class="edit__feedback">
        {% for error in form.comment.errors %}
        <span>{{ error }}</span>
        {% endfor %}
      </div>
    </div>

    <div class="edit__group btn-container">
      <div class="edit__submit-btn reload-button">
        <a
          type="button"
          href="{{ url_for('account.show_qrcode', account_id=account_id) }}"
          class="edit__submit"
          >QR Code</a
        >
      </div>
    </div>

    <div class="edit__group btn-container">
      <div class="edit__submit-btn reload-button">
        <a
          type="button"
          href="{{ url_for('account.device', account_id=account_id) }}"
          class="edit__submit"
          >Device</a
        >
      </div>
    </div>

    <div>
      <img src="{{ url_for('static', filename='images/loading-11.gif') }} " id="gif">
    </div>
    <div class="edit__group btn-container">
      <div class="edit__submit-btn reload-button">{{ form.submit(class="edit__submit")}}</div>
    </div>
  </div>
</form>

<form class="edit__form" action="{{ url_for('account.extend_sub', account_id=account_id) }}" method="POST">
  <div class="edit__container">
    {{ sub_form.hidden_tag() }}
    <div class="edit__group">
      <div class="input__wrapper">
        <label class="edit__label"> Renew Subscription </label>
        {{ sub_form.sub_duration(class="edit__input")}}
      </div>
      <div class="edit__feedback">
        {% for error in sub_form.sub_duration.errors %}
        <span>{{ error }}</span>
        {% endfor %}
      </div>
    </div>

    <div class="edit__group">
      <div class="input__wrapper">
        <label class="edit__label"> Subscription Activation Date </label>
        {{ sub_form.sub_activate_date(class="edit__input", type="date")}}
      </div>
      <div class="edit__feedback">
        {% for error in sub_form.sub_activate_date.errors %}
        <span>{{ error }}</span>
        {% endfor %}
      </div>
    </div>

    <div class="edit__group">
      <div class="input__wrapper">
        <label class="edit__label"> {{ expiration_date }}</label>
      </div>
    </div>

    <div>
      <img src="{{ url_for('static', filename='images/loading-11.gif') }} " id="gif">
    </div>
    <div class="edit__group btn-container">
      <div class="edit__submit-btn reload-button">{{ sub_form.submit(class="edit__submit")}}</div>
    </div>

  </div>
</form>

app/templates/components/_account-qrcode.html
<div class=qrcode-container>
    <img src="data:image/jpeg;base64,{{ img_data }}">
</div>
<div class="btn-container">
    <div class="edit__submit-btn reload-button">
        <a
        type="button"
        href="{{ action_url }}"
        class="edit__submit"
        >Edit Account</a
        >
    </div>
</div>

app/templates/components/_header.html
<header class="header">
  <div class="container container--lg">
    <div class="header__inner">
      {% if current_user.is_authenticated %}
      <button class="menu-btn" type="button">
        <span class="menu-btn-line"></span>
      </button>
      <nav class="menu">
        <ul class="menu__list">
          {% if current_user.role == current_user.RoleType.admin %}
          <li class="menu__item">
            <a class="menu__link" href="{{ url_for('user.index') }}">Users</a>
          </li>
          <li class="menu__item">
            <a class="menu__link" href="{{ url_for('distributor.index') }}"
              >Distributors</a
            >
          </li>
          <li class="menu__item">
            <a class="menu__link" href="{{ url_for('reseller.index') }}"
              >Resellers</a
            >
          </li>
          <li class="menu__item">
            <a class="menu__link" href="{{ url_for('sub_reseller.index') }}"
              >Sub Resellers</a
            >
          </li>
          <li class="menu__item">
            <a class="menu__link" href="{{ url_for('support.index') }}"
              >Supports</a
            >
          </li>
          <li class="menu__item">
            <a class="menu__link" href="{{ url_for('account.index') }}"
              >Accounts</a
            >
          </li>
          <li class="menu__item">
            <a class="menu__link" href="{{ url_for('product.index') }}"
              >Products</a
            >
          </li>
          {% endif %} {% if current_user.role == current_user.RoleType.support
          %}
          <li class="menu__item">
            <a class="menu__link" href="{{ url_for('account.index') }}"
              >Accounts</a
            >
          </li>
          <li class="menu__item">
            <a class="menu__link" href="{{ url_for('product.index') }}"
              >Products</a
            >
          </li>
          {% endif %} {% if current_user.role ==
          current_user.RoleType.distributor %}
          <li class="menu__item">
            <a class="menu__link" href="{{ url_for('reseller.index') }}"
              >Resellers</a
            >
          </li>
          <li class="menu__item">
            <a class="menu__link" href="{{ url_for('sub_reseller.index') }}"
              >Sub Resellers</a
            >
          </li>
          <li class="menu__item">
            <a class="menu__link" href="{{ url_for('account.index') }}"
              >Accounts</a
            >
          </li>
          {% endif %} {% if current_user.role == current_user.RoleType.reseller
          %}
          <li class="menu__item">
            <a class="menu__link" href="{{ url_for('sub_reseller.index') }}"
              >Sub Resellers</a
            >
          </li>
          <li class="menu__item">
            <a class="menu__link" href="{{ url_for('account.index') }}"
              >Accounts</a
            >
          </li>
          {% endif %} {% if current_user.role ==
          current_user.RoleType.sub_reseller %}
          <li class="menu__item">
            <a class="menu__link" href="{{ url_for('account.index') }}"
              >Accounts</a
            >
          </li>
          {% endif %}
        </ul>
      </nav>
      <div class="overlay"></div>
      {% endif %}
      <div>
        <a class="logo" href="#">
          <img
            class="logo__img"
            src="{{ url_for('static', filename='images/icons/logo.svg') }}"
            alt="Kryptr Logo"
          />
        </a>
      </div>
      {% if current_user.is_authenticated %}
      <div class="account-wrapper">
        <button class="account-drp" onclick="showFuncs()">
          {{ current_user.username }}
        </button>
        <div id="funcs-drp" class="account-drp__content">
          <a href="{{ url_for('auth.logout') }}">Logout</a>
        </div>
      </div>

      {% else %}
      <button class="account">Log in</button>
      {% endif %}
    </div>
  </div>
</header>